### ISSUE TITLE
[Modifier] heightIn(widthIn) 과 defaultMinSize 의 차이에 대한 문의

### ISSUE THREAD

**Issue by jeongth9446** [gdgand/ComposeCamp2022#56]
## 질문 내용
- 안녕하세요. Modifier 의 heightIn (widthIn) 관련 질문드립니다.
- 기존에 개발을 할 때 Modifier.defaultMinSize 수정자를 이용하여 개발을 진행해왔는데요. 우선 UI 동작으로 볼 때는 heightIn/widthIn 과 defaultMinSize가 같게 동작하는 것을 확인할 수 있었습니다.
- 개발을 진행하면서 사소한 성능에도 신경을 쓰다보니, 어떤 것을 사용하는 것이 더 좋은 방법인지 알고 싶습니다. (min 만 규제하면 될 때)

## 코드랩 링크
- [해당 페이지 링크](https://developer.android.com/codelabs/jetpack-compose-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fjetpack-compose-for-android-developers-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-layouts#4)

## 스크린샷 또는 코드 스니펫 
- ![image](https://user-images.githubusercontent.com/52663419/202440206-72ecd21e-c16c-4abc-b033-769b57ede9e2.png)

## 올리기 전 체크사항 
- [ O ] 기존에 같은 질문이 있었는 지 확인했습니다. 
- [ O ] Label 을 맞게 설정했습니다.

**Comment by Veronikapj** [comment]
두 함수에 대한 문서를 참고해보면 좋을 것 같아요. 제가 생각하기에는 성능이 좋다 나쁘다의 차이보다는 사용할 수 있는 케이스가 다를 수 있을 걸로 보입니다. 
- [Modifier.defaultMinSize](https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier#(androidx.compose.ui.Modifier).defaultMinSize(androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp)) : 제약 조건이 없을 때 default min 사이즈 지정이 가능합니다. 
- [Modifier.widthIn](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.ui.Modifier).widthIn(androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp)) : 제약 조건이 있을 때 `min`~`max` 의 사이즈 범위 지정이 가능합니다.

**Comment by jeongth9446** [comment]
감사합니다.
