### ISSUE TITLE
중급코스 Pathway 1-2 "Jetpack Compose 테마 설정" 중 Modifier.clip 질문

### ISSUE THREAD

**Issue by roeniss** [gdgand/ComposeCamp2022#65]
## 질문 내용
- 아래 1번 사진과 같은 위치의 clip 함수에 대한 질문입니다. 저는 네 모서리에 clip 이 적용될거라 기대했는데 우상단(topStart) 만 적용되는 이유가 궁금합니다.

<img width="1462" alt="CleanShot 2022-11-20 at 16 20 02@2x" src="https://user-images.githubusercontent.com/26613280/202890642-637eb652-af2a-49d4-9e98-3e08de9c9fbd.png">

## 코드랩 링크
- [사진1의 위치 바로가기](https://developer.android.com/codelabs/jetpack-compose-theming?hl=ko&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fjetpack-compose-for-android-developers-1%3Fhl%3Dko%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-theming#6)

## 스크린샷 또는 코드 스니펫 

- before: 
![CleanShot 2022-11-20 at 16 21 47@2x](https://user-images.githubusercontent.com/26613280/202890686-43cd9a9c-f5cd-4a02-86a0-a3f39ec8f7e5.png)

- after:
![CleanShot 2022-11-20 at 16 21 19@2x](https://user-images.githubusercontent.com/26613280/202890676-a8cabf4b-d9fd-4e89-94ce-9f7d84ee73fe.png)

## 올리기 전 체크사항 
- [x] 기존에 같은 질문이 있었는지 확인했습니다. 
- [x] Label 을 맞게 설정했습니다.
  - **라벨이 잘못 달려있는데, 제가 수정할 수가 없습니다. 권한 확인 부탁드립니다.**

**Comment by NetLSS** [comment]
`JetnewsShapes` 로 정의 해준 `Shapes` 객체의 `small` 값이 `CutCornerShape(topStart = 8.dp)` 으로 설정되어 있어서 좌상단 부분만 잘려 나가서 그렇습니다.

```kt
val JetnewsShapes = Shapes(
    small = CutCornerShape(topStart = 8.dp),
    medium = CutCornerShape(topStart = 24.dp),
    large = RoundedCornerShape(8.dp)
)
```

또한 `MaterialTheme.shapes.small` 에서 MaterialTheme 는 현재 상위에 지정된 테마에 접근하기 때문에 `Home()` 에서 사용 중인 `JetnewsTheme` 테마를 사용하게 됩니다.

**Comment by roeniss** [comment]
@NetLSS  아 그 쪽에 있었군요. 감사합니다. 

> 현재 상위에 지정된 테마에 접근하기 때문에

따로 Local 값을 제공해주지 않으면 적절한 설정값을 찾을때까지 parent 를 타고 계속 올라간다고 이해해도 될까요?

**Comment by NetLSS** [comment]
> @NetLSS 아 그 쪽에 있었군요. 감사합니다.
> 
> > 현재 상위에 지정된 테마에 접근하기 때문에
> 
> 따로 Local 값을 제공해주지 않으면 적절한 설정값을 찾을때까지 parent 를 타고 계속 올라간다고 이해해도 될까요?

넵 저도 그렇게 이해했어요. 현재 스코프에 지정된 테마를 참조하는 듯 합니다.
